### ISSUE TITLE
Fix thy tests

### ISSUE THREAD

**Issue by eriwen** [gradle-guides/gradle-site-plugin#3]
A few tests are failing as we can see in the [build scan](https://scans.gradle.com/s/oyyfygf6mmthu).

The cause was not immediately clear to me, but I feel like we oughta stay green if we can.

**Comment by bmuschko** [comment]
How come tests are failing all a sudden? Did you upgrade Gradle recently?

**Comment by eriwen** [comment]
I did. How does that factor in here, since I think it was a minor release upgrade?

**Comment by bmuschko** [comment]
I didn't have a deeper look yet. The other problem might be the upgrade of the guide plugin. I will have a look later this week.

**Comment by eriwen** [comment]
This is not urgent. Please defer unless it's the most important thing you have to do.

**Comment by bmuschko** [comment]
The reason was probably this [change in 4.5](https://docs.gradle.org/4.5/release-notes.html):

> Use of runtime types when declaring @Nested task inputs
>
> When analyzing @Nested task properties for declared input and output sub-properties, Gradle used to only observe the declared type of the property. This meant ignoring any sub-properties declared by a runtime sub-type.
>
> Since Gradle 4.5, Gradle uses the type of the actual value instead, and hence can discover all sub-properties declared this way.
